Organizations:
  - &OrdererOrg
    Name: Orderer
    ID: OrdererMSP
    MSPDir: crypto-config/ordererOrganizations/pharma-network.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"

  - &manufacturer
    Name: manufacturerMSP
    ID: manufacturerMSP
    MSPDir: crypto-config/peerOrganizations/manufacturer.pharma-network.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('manufacturerMSP.admin', 'manufacturerMSP.peer', 'manufacturerMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('manufacturerMSP.admin', 'manufacturerMSP.peer', 'manufacturerMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('manufacturerMSP.admin', 'manufacturerMSP.peer', 'manufacturerMSP.client')"
    AnchorPeers:
      - Host: peer0.manufacturer.pharma-network.com
        Port: 7051

  - &distributor
    Name: distributorMSP
    ID: distributorMSP
    MSPDir: crypto-config/peerOrganizations/distributor.pharma-network.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('distributorMSP.admin', 'distributorMSP.peer', 'distributorMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('distributorMSP.admin', 'distributorMSP.peer', 'distributorMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('distributorMSP.admin', 'distributorMSP.peer', 'distributorMSP.client')"
    AnchorPeers:
      - Host: peer0.distributor.pharma-network.com
        Port: 9051

  - &retailer
    Name: retailerMSP
    ID: retailerMSP
    MSPDir: crypto-config/peerOrganizations/retailer.pharma-network.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('retailerMSP.admin', 'retailerMSP.peer', 'retailerMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('retailerMSP.admin', 'retailerMSP.peer', 'retailerMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('retailerMSP.admin', 'retailerMSP.peer', 'retailerMSP.client')"
    AnchorPeers:
      - Host: peer0.retailer.pharma-network.com
        Port: 11051

  - &consumer
    Name: consumerMSP
    ID: consumerMSP
    MSPDir: crypto-config/peerOrganizations/consumer.pharma-network.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('consumerMSP.admin', 'consumerMSP.peer', 'consumerMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('consumerMSP.admin', 'consumerMSP.peer', 'consumerMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('consumerMSP.admin', 'consumerMSP.peer', 'consumerMSP.client')"
    AnchorPeers:
      - Host: peer0.consumer.pharma-network.com
        Port: 13051

  - &transporter
    Name: transporterMSP
    ID: transporterMSP
    MSPDir: crypto-config/peerOrganizations/transporter.pharma-network.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('transporterMSP.admin', 'transporterMSP.peer', 'transporterMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('transporterMSP.admin', 'transporterMSP.peer', 'transporterMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('transporterMSP.admin', 'transporterMSP.peer', 'transporterMSP.client')"
    AnchorPeers:
      - Host: peer0.transporter.pharma-network.com
        Port: 15051

#Capabilities

Capabilities:
  Channel: &ChannelCapabilities
    V1_4_3: true
    V1_3: false
    V1_1: false
  Orderer: &OrdererCapabilities
    V1_4_2: true
    V1_1: false
  Application: &ApplicationCapabilities
    V1_4_2: true
    V1_3: false
    V1_2: false
    V1_1: false

#Application

Application: &ApplicationDefaults
  Organizations:
  Policies: &ApplicationDefaultPolicies
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "ANY Admins"
  Capabilities: *ApplicationCapabilities

#Orderer
Orderer: &OrdererDefaults
  OrdererType: solo
  Addresses:
    - orderer.pharma-network.com:7050
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB
  Organizations:
  Capabilities: *OrdererCapabilities
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "ANY Admins"
    # BlockValidation specifies what signatures must be included in the block
    # from the orderer for the peer to validate it.
    BlockValidation:
      Type: ImplicitMeta
      Rule: "ANY Writers"

Channel: &ChannelDefaults
  Policies:
    # Who may invoke the 'Deliver' API
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    # Who may invoke the 'Broadcast' API
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    # By default, who may modify elements at this config level
    Admins:
      Type: ImplicitMeta
      Rule: "ANY Admins"
  Capabilities:
    <<: *ChannelCapabilities


#Profiles
Profiles:
  OrdererGenesis:
    <<: *ChannelDefaults
    Capabilities:
      <<: *ChannelCapabilities
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *OrdererOrg
      Capabilities:
        <<: *OrdererCapabilities
    Consortiums:
      PharmaConsortium:
        Organizations:
          - *manufacturer
          - *distributor
          - *retailer
          - *consumer
          - *transporter

  pharmachannel:
    Consortium: PharmaConsortium
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *manufacturer
        - *distributor
        - *retailer
        - *consumer
        - *transporter
      Capabilities:
        <<: *ApplicationCapabilities
