NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.retailer.pharma-network.com-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.retailer.pharma-network.com-cert.pem
    OrganizationalUnitIdentifier: peer
